version: '3.8'

services:
  web:
    image: warnerb47/logidoo-web:1.0.3
    ports:
      - "80:80"
    deploy:
      replicas: 3
  api:
    image: warnerb47/logidoo-api:1.0.2
    ports:
      - "5000:9000"
    deploy:
      replicas: 3
  cron:
    image: warnerb47/logidoo-cron:1.0.2
    ports:
      - "4040:4040"
    deploy:
      replicas: 3