version: '3.8'

services:
  web:
    image: warnerb47/zoom-clone:staging_latest
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
  proxy:
    image: nginx:1.23.0
    volumes:
      - /data/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]