---
version: '3.8'

services:
  ################################################################
  # The promethes cadvisor 
  # For each node a separte service need to be added 
  ################################################################
  # START cadvisor.....    
  manager_cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.39.3
    container_name: manager_cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    deploy:
      placement:
        constraints:
          - node.hostname == manager
    devices:
      - /dev/kmsg


  worker1_cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.39.3
    container_name: worker1_cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    deploy:
      placement:
        constraints:
          - node.hostname == worker1
    devices:
      - /dev/kmsg


  worker2_cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.39.3
    container_name: worker2_cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    deploy:
      placement:
        constraints:
          - node.hostname == worker2
    devices:
      - /dev/kmsg