# https://github.com/atosatto/ansible-dockerswarm/blob/master/tasks/setup-swarm-cluster.yml
---
- hosts: all
  gather_facts: yes
  become: yes
  vars:
    docker_swarm_port: 2377
    master_ip: 3.128.160.212
  tasks:
    - name: install pip3
      apt: 
        name: python3-pip
        state: present 
    - name: Install docker python package
      pip:
        name: docker
    - name: Init a new swarm with default parameters
      docker_swarm:
        advertise_addr: '{{ansible_host}}'
        state: present
      register: swarm_init
      when: "inventory_hostname == groups['masters'][0]"
    - name: Get the worker join-token.
      shell: docker swarm join-token -q worker
      changed_when: false
      register: docker_worker_token
      delegate_to: "{{ groups['masters'][0] }}"
      delegate_facts: true
      when: "inventory_hostname in groups['workers']"
    - name: Add worker node
      docker_swarm:
        state: join
        advertise_addr: '{{ansible_host}}'
        join_token: '{{docker_worker_token.stdout}}'
        remote_addrs: ['{{master_ip}}:{{docker_swarm_port}}']
      register: swarm_add
      when: "inventory_hostname in groups['workers']"

