# https://github.com/atosatto/ansible-dockerswarm/blob/master/tasks/setup-swarm-cluster.yml
---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: install pip3
      apt: 
        name: python3-pip
        state: present 
    - name: Install docker python package
      pip:
        name: docker
    - name: Init a new swarm with default parameters
      docker_swarm:
        advertise_addr: '{{ansible_host}}'
        state: present
      register: swarm_init
      when: "inventory_hostname == groups['masters'][0]"


