version: '3.8'
# sudo docker stack deploy -c filebeat-stack.yml filebeat
# sudo docker stack rm filebeat
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    deploy:
      replicas: 1
    volumes:
      - nginx_data:/var/log/nginx
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.4
    # Run as 'root' instead of 'filebeat' (uid 1000) to allow reading
    # 'docker.sock' and the host's filesystem.
    user: root
    command:
      # Log to stderr.
      - -e
      # Disable config file permissions checks. Allows mounting
      # 'config/filebeat.yml' even if it's not owned by root.
      # see: https://www.elastic.co/guide/en/beats/libbeat/current/config-file-permissions.html
      - --strict.perms=false
    configs:
      - source: filebeat_config
        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - nginx_data:/nginxLog
configs:
  filebeat_config:
    file: /etc/filebeat/config/filebeat.yml
volumes:
  nginx_data: