Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  # monitoring VM
  config.vm.define "monitoring" do |monitoring|
    monitoring.vm.provider "virtualbox" do |vb|
      # vb.memory = "512"
      vb.name = "monitoring"
    end
    monitoring.vm.network "private_network", ip: "192.168.33.21"
    monitoring.vm.hostname = "monitoring"
  end



end
