Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  # monitoring VM
  config.vm.define "monitoring" do |monitoring|
    monitoring.vm.provider "virtualbox" do |vb|
      # vb.memory = "512"
      vb.name = "monitoring"
    end
    monitoring.vm.network "private_network", ip: "192.168.33.20"
    monitoring.vm.hostname = "monitoring"
    monitoring.vm.provision "shell", inline: <<-SHELL
      echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3TYmESsR2bqxEbxU1V/gQWmGyMNNS9nX4qt4Oz+6sOohM4snRTHPdL7IoDADUIa0dlGHWltfwwnAOjaUcOUTjfzzza5xi7pp0Ed5Rqaf+zbdmY3bjWPe8KCNYhygy4GE2ligLrDelK8gYoe0ZNPHCLPvo4nHbQCn439rksODwZAxpsauwzP4Y8AGvZ4FfdiVooJs1DUypVDrmUvMOALWI2KNOI06MNcD/VoYgQi8SWnAXgFw4EdBM58rprwZdtagjys798JC46IVLb467taPwZcOwSQAxAf0/JmR3XSl4uLvw/7yf3lMn6S2m1lL92IWcmiqyzgujQbWNRbOjuyIJ' >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end



end
