Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  # master VM
  config.vm.define "master" do |master|
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "master"
    end
    master.vm.network "private_network", ip: "192.168.33.20"
    master.vm.hostname = "master"
    master.vm.provision "shell", inline: <<-SHELL
      echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3TYmESsR2bqxEbxU1V/gQWmGyMNNS9nX4qt4Oz+6sOohM4snRTHPdL7IoDADUIa0dlGHWltfwwnAOjaUcOUTjfzzza5xi7pp0Ed5Rqaf+zbdmY3bjWPe8KCNYhygy4GE2ligLrDelK8gYoe0ZNPHCLPvo4nHbQCn439rksODwZAxpsauwzP4Y8AGvZ4FfdiVooJs1DUypVDrmUvMOALWI2KNOI06MNcD/VoYgQi8SWnAXgFw4EdBM58rprwZdtagjys798JC46IVLb467taPwZcOwSQAxAf0/JmR3XSl4uLvw/7yf3lMn6S2m1lL92IWcmiqyzgujQbWNRbOjuyIJ' >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  # # worker1 VM
  # config.vm.define "worker1" do |worker1|
  #   worker1.vm.provider "virtualbox" do |vb|
  #     vb.memory = "1024"
  #     vb.name = "worker1"
  #   end
  #   worker1.vm.network "private_network", ip: "192.168.33.21"
  #   worker1.vm.hostname = "worker1"
  #   worker1.vm.provision "shell", inline: <<-SHELL
  #     echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3TYmESsR2bqxEbxU1V/gQWmGyMNNS9nX4qt4Oz+6sOohM4snRTHPdL7IoDADUIa0dlGHWltfwwnAOjaUcOUTjfzzza5xi7pp0Ed5Rqaf+zbdmY3bjWPe8KCNYhygy4GE2ligLrDelK8gYoe0ZNPHCLPvo4nHbQCn439rksODwZAxpsauwzP4Y8AGvZ4FfdiVooJs1DUypVDrmUvMOALWI2KNOI06MNcD/VoYgQi8SWnAXgFw4EdBM58rprwZdtagjys798JC46IVLb467taPwZcOwSQAxAf0/JmR3XSl4uLvw/7yf3lMn6S2m1lL92IWcmiqyzgujQbWNRbOjuyIJ' >> /home/vagrant/.ssh/authorized_keys
  #   SHELL
  # end

end
